---
# Copyright 2014, Rackspace US, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

- name: Get Modern PIP
  get_url:
    url: "{{ pip_upstream_url }}"
    dest: "/opt/get-pip.py"
    force: "yes"
    validate_certs: "{{ pip_validate_certs }}"
  register: get_pip
  until: get_pip | success
  ignore_errors: True
  retries: 5
  delay: 2
  tags:
    - pip-install-script

- name: Get Modern PIP using fallback URL
  get_url:
    url: "{{ pip_fallback_url }}"
    dest: "/opt/get-pip.py"
    force: "yes"
    validate_certs: "{{ pip_validate_certs }}"
  when: get_pip | failed
  register: get_pip_fallback
  until: get_pip_fallback | success
  retries: 5
  delay: 2
  tags:
    - pip-install-script

- name: Install PIP
  shell: "python /opt/get-pip.py {{ pip_get_pip_options }} {{ pip_packages | map('quote') | join (' ') }}"
  ignore_errors: true
  register: pip_install
  until: pip_install | success
  retries: 3
  delay: 2

- name: Install PIP (fall back mode)
  shell: "python /opt/get-pip.py --isolated {{ pip_get_pip_options }} {{ pip_packages | map('quote') | join (' ') }}"
  when: pip_install.rc != 0
  register: pip_install_fall_back
  until: pip_install_fall_back | success
  retries: 3
  delay: 2
